/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as RecruiterIdRouteImport } from './routes/recruiter/$id'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as CompanyIdRouteImport } from './routes/company/$id'

const AuthRegisterLazyRouteImport = createFileRoute('/auth/register')()
const AuthLoginLazyRouteImport = createFileRoute('/auth/login')()
const AuthResetPasswordLazyRouteImport = createFileRoute(
  '/auth/ResetPassword',
)()
const AuthForgotPasswordLazyRouteImport = createFileRoute(
  '/auth/ForgotPassword',
)()

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/recruiter/',
  path: '/recruiter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/jobs/index.lazy').then((d) => d.Route))
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterLazyRoute = AuthRegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/register.lazy').then((d) => d.Route))
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))
const AuthResetPasswordLazyRoute = AuthResetPasswordLazyRouteImport.update({
  id: '/ResetPassword',
  path: '/ResetPassword',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/auth/ResetPassword.lazy').then((d) => d.Route),
)
const AuthForgotPasswordLazyRoute = AuthForgotPasswordLazyRouteImport.update({
  id: '/ForgotPassword',
  path: '/ForgotPassword',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() =>
  import('./routes/auth/ForgotPassword.lazy').then((d) => d.Route),
)
const RecruiterIdRoute = RecruiterIdRouteImport.update({
  id: '/recruiter/$id',
  path: '/recruiter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIdRoute = CompanyIdRouteImport.update({
  id: '/company/$id',
  path: '/company/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/company/$id': typeof CompanyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/recruiter/$id': typeof RecruiterIdRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordLazyRoute
  '/auth/ResetPassword': typeof AuthResetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/blogs': typeof BlogsIndexRoute
  '/company': typeof CompanyIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/company/$id': typeof CompanyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/recruiter/$id': typeof RecruiterIdRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordLazyRoute
  '/auth/ResetPassword': typeof AuthResetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/blogs': typeof BlogsIndexRoute
  '/company': typeof CompanyIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/company/$id': typeof CompanyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/recruiter/$id': typeof RecruiterIdRoute
  '/auth/ForgotPassword': typeof AuthForgotPasswordLazyRoute
  '/auth/ResetPassword': typeof AuthResetPasswordLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/blogs/': typeof BlogsIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/company/$id'
    | '/jobs/$id'
    | '/recruiter/$id'
    | '/auth/ForgotPassword'
    | '/auth/ResetPassword'
    | '/auth/login'
    | '/auth/register'
    | '/blogs'
    | '/company'
    | '/jobs'
    | '/profile'
    | '/recruiter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/company/$id'
    | '/jobs/$id'
    | '/recruiter/$id'
    | '/auth/ForgotPassword'
    | '/auth/ResetPassword'
    | '/auth/login'
    | '/auth/register'
    | '/blogs'
    | '/company'
    | '/jobs'
    | '/profile'
    | '/recruiter'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/company/$id'
    | '/jobs/$id'
    | '/recruiter/$id'
    | '/auth/ForgotPassword'
    | '/auth/ResetPassword'
    | '/auth/login'
    | '/auth/register'
    | '/blogs/'
    | '/company/'
    | '/jobs/'
    | '/profile/'
    | '/recruiter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CompanyIdRoute: typeof CompanyIdRoute
  JobsIdRoute: typeof JobsIdRoute
  RecruiterIdRoute: typeof RecruiterIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/ResetPassword': {
      id: '/auth/ResetPassword'
      path: '/ResetPassword'
      fullPath: '/auth/ResetPassword'
      preLoaderRoute: typeof AuthResetPasswordLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/ForgotPassword': {
      id: '/auth/ForgotPassword'
      path: '/ForgotPassword'
      fullPath: '/auth/ForgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordLazyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/recruiter/$id': {
      id: '/recruiter/$id'
      path: '/recruiter/$id'
      fullPath: '/recruiter/$id'
      preLoaderRoute: typeof RecruiterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$id': {
      id: '/company/$id'
      path: '/company/$id'
      fullPath: '/company/$id'
      preLoaderRoute: typeof CompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordLazyRoute: typeof AuthForgotPasswordLazyRoute
  AuthResetPasswordLazyRoute: typeof AuthResetPasswordLazyRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthRegisterLazyRoute: typeof AuthRegisterLazyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordLazyRoute: AuthForgotPasswordLazyRoute,
  AuthResetPasswordLazyRoute: AuthResetPasswordLazyRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthRegisterLazyRoute: AuthRegisterLazyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CompanyIdRoute: CompanyIdRoute,
  JobsIdRoute: JobsIdRoute,
  RecruiterIdRoute: RecruiterIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
